-- Migration: grocery_products
-- Created: 2025-05-22

CREATE TABLE IF NOT EXISTS grocery_products (
  id TEXT PRIMARY KEY,
  store_id TEXT NOT NULL,
  name TEXT NOT NULL,
  brand TEXT NOT NULL DEFAULT '',
  package_size TEXT NOT NULL,
  package_qty NUMERIC NOT NULL,
  package_unit TEXT NOT NULL,
  price NUMERIC NOT NULL,
  price_per_unit NUMERIC NOT NULL,
  is_organic BOOLEAN DEFAULT false,
  is_local BOOLEAN DEFAULT false,
  tags TEXT[] NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE grocery_products ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='grocery_products' AND policyname='Public read grocery_products') THEN
    CREATE POLICY "Public read grocery_products" ON grocery_products FOR SELECT USING (true);
  END IF;
END $$;

INSERT INTO grocery_products (id, store_id, name, brand, package_size, package_qty, package_unit, price, price_per_unit, is_organic, is_local, tags) VALUES
('skyr-metro', 'metro', 'Skyr nature', 'Siggi''s', '500g', 500, 'g', 6.49, 0.01298, false, false, ARRAY['skyr','yogourt','protéines']),
('skyr-iga', 'iga', 'Skyr nature 0%', 'Skyr.is', '500g', 500, 'g', 5.99, 0.01198, false, false, ARRAY['skyr','yogourt','protéines']),
('skyr-walmart', 'walmart', 'Skyr Icelandic', 'President''s Choice', '650g', 650, 'g', 5.47, 0.00842, false, false, ARRAY['skyr','yogourt','protéines']),
('skyr-superc', 'superc', 'Skyr nature', 'Compliments', '500g', 500, 'g', 4.99, 0.00998, false, false, ARRAY['skyr','yogourt','protéines']),
('skyr-maxi', 'maxi', 'Skyr nature', 'Skyr.is', '500g', 500, 'g', 5.79, 0.01158, false, false, ARRAY['skyr','yogourt','protéines']),
('greek-metro', 'metro', 'Yogourt grec nature 0%', 'Fage', '750g', 750, 'g', 7.99, 0.01065, false, false, ARRAY['yogourt','grec','protéines']),
('greek-iga', 'iga', 'Yogourt grec nature', 'Liberté', '750g', 750, 'g', 7.49, 0.00999, false, true, ARRAY['yogourt','grec','protéines']),
('greek-walmart', 'walmart', 'Greek Yogurt Plain', 'Great Value', '750g', 750, 'g', 5.97, 0.00796, false, false, ARRAY['yogourt','grec','protéines']),
('greek-superc', 'superc', 'Yogourt grec 2%', 'Oikos', '750g', 750, 'g', 7.29, 0.00972, false, false, ARRAY['yogourt','grec','protéines']),
('greek-maxi', 'maxi', 'Yogourt grec nature', 'Oikos', '750g', 750, 'g', 6.99, 0.00932, false, false, ARRAY['yogourt','grec','protéines']),
('fb-metro', 'metro', 'Fromage blanc 0%', 'Liberté', '500g', 500, 'g', 4.99, 0.00998, false, true, ARRAY['fromage blanc','protéines','dairy']),
('fb-iga', 'iga', 'Fromage blanc nature', 'Riviera', '450g', 450, 'g', 4.79, 0.01064, false, true, ARRAY['fromage blanc','protéines','dairy']),
('fb-walmart', 'walmart', 'Quark Fromage Frais', 'Great Value', '500g', 500, 'g', 3.97, 0.00794, false, false, ARRAY['fromage blanc','protéines','dairy']),
('cottage-metro', 'metro', 'Fromage cottage 1%', 'Nordica', '500g', 500, 'g', 4.99, 0.00998, false, false, ARRAY['fromage cottage','protéines','dairy']),
('cottage-walmart', 'walmart', 'Cottage Cheese 2%', 'Great Value', '500g', 500, 'g', 3.97, 0.00794, false, false, ARRAY['fromage cottage','protéines','dairy']),
('cottage-iga', 'iga', 'Fromage cottage légère', 'Quebon', '500g', 500, 'g', 4.69, 0.00938, false, true, ARRAY['fromage cottage','protéines','dairy']),
('feta-metro', 'metro', 'Feta grecque', 'Krinos', '200g', 200, 'g', 5.49, 0.02745, false, false, ARRAY['feta','fromage']),
('feta-walmart', 'walmart', 'Feta Cheese', 'Great Value', '200g', 200, 'g', 3.97, 0.01985, false, false, ARRAY['feta','fromage']),
('feta-iga', 'iga', 'Feta AOP grecque', 'Dodoni', '200g', 200, 'g', 6.29, 0.03145, false, false, ARRAY['feta','fromage']),
('eggs-metro', 'metro', 'Œufs extra-gros', 'Burnbrae', '12 unités', 12, 'unités', 5.49, 0.4575, false, true, ARRAY['oeufs','protéines']),
('eggs-iga', 'iga', 'Œufs gros blancs', 'Ferme Bertrand', '12 unités', 12, 'unités', 4.99, 0.4158, false, true, ARRAY['oeufs','protéines']),
('eggs-walmart', 'walmart', 'Large White Eggs', 'Great Value', '12 unités', 12, 'unités', 3.97, 0.3308, false, false, ARRAY['oeufs','protéines']),
('eggs-superc', 'superc', 'Œufs extra-gros', 'Selection', '12 unités', 12, 'unités', 4.49, 0.3742, false, false, ARRAY['oeufs','protéines']),
('eggs-maxi', 'maxi', 'Œufs gros', 'Compliments', '12 unités', 12, 'unités', 4.29, 0.3575, false, false, ARRAY['oeufs','protéines']),
('eggs-org-metro', 'metro', 'Œufs biologiques', 'Natura', '12 unités', 12, 'unités', 8.49, 0.7075, true, true, ARRAY['oeufs','bio','protéines']),
('oats-metro', 'metro', 'Flocons d''avoine à l''ancienne', 'Quaker', '1kg', 1000, 'g', 5.49, 0.00549, false, false, ARRAY['avoine','flocons','céréales']),
('oats-iga', 'iga', 'Gruau à l''ancienne', 'Robin Hood', '1kg', 1000, 'g', 4.99, 0.00499, false, false, ARRAY['avoine','flocons','céréales']),
('oats-walmart', 'walmart', 'Old-fashioned Oats', 'Great Value', '1.36kg', 1360, 'g', 4.27, 0.00314, false, false, ARRAY['avoine','flocons','céréales']),
('oats-superc', 'superc', 'Flocons d''avoine', 'Selection', '1kg', 1000, 'g', 4.49, 0.00449, false, false, ARRAY['avoine','flocons','céréales']),
('oats-maxi', 'maxi', 'Gruau à l''ancienne', 'Quaker', '1kg', 1000, 'g', 5.19, 0.00519, false, false, ARRAY['avoine','flocons','céréales']),
('granola-metro', 'metro', 'Granola faible en sucre', 'Nature Valley', '450g', 450, 'g', 6.99, 0.01553, false, false, ARRAY['granola','céréales']),
('granola-iga', 'iga', 'Granola aux fruits', 'Quaker', '400g', 400, 'g', 6.49, 0.01623, false, false, ARRAY['granola','céréales']),
('granola-walmart', 'walmart', 'Granola Original', 'Great Value', '500g', 500, 'g', 4.97, 0.00994, false, false, ARRAY['granola','céréales']),
('quinoa-metro', 'metro', 'Quinoa blanc', 'Alter Eco', '340g', 340, 'g', 7.99, 0.02350, true, false, ARRAY['quinoa','céréales','glucides']),
('quinoa-walmart', 'walmart', 'Quinoa White', 'Great Value', '500g', 500, 'g', 5.97, 0.01194, false, false, ARRAY['quinoa','céréales','glucides']),
('quinoa-iga', 'iga', 'Quinoa biologique', 'Irresistibles', '340g', 340, 'g', 8.49, 0.02497, true, false, ARRAY['quinoa','bio','céréales','glucides']),
('quinoa-superc', 'superc', 'Quinoa', 'Selection', '500g', 500, 'g', 5.49, 0.01098, false, false, ARRAY['quinoa','céréales','glucides']),
('lentil-metro', 'metro', 'Lentilles vertes du Puy', 'Unico', '400g', 400, 'g', 2.99, 0.00748, false, false, ARRAY['lentilles','légumineuses','protéines']),
('lentil-walmart', 'walmart', 'Green Lentils', 'Great Value', '500g', 500, 'g', 1.97, 0.00394, false, false, ARRAY['lentilles','légumineuses','protéines']),
('lentil-iga', 'iga', 'Lentilles rouges', 'Irresistibles', '400g', 400, 'g', 2.79, 0.00698, false, false, ARRAY['lentilles','légumineuses','protéines']),
('lentil-can-metro', 'metro', 'Lentilles cuites en conserve', 'Unico', '540ml', 540, 'ml', 1.99, 0.00369, false, false, ARRAY['lentilles','légumineuses','conserve']),
('chickpeas-metro', 'metro', 'Pois chiches en conserve', 'Unico', '540ml', 540, 'ml', 1.99, 0.00369, false, false, ARRAY['pois chiches','légumineuses','protéines']),
('chickpeas-walmart', 'walmart', 'Chickpeas Canned', 'Great Value', '540ml', 540, 'ml', 1.27, 0.00235, false, false, ARRAY['pois chiches','légumineuses','protéines']),
('chickpeas-iga', 'iga', 'Pois chiches cuits', 'Compliments', '540ml', 540, 'ml', 1.79, 0.00331, false, false, ARRAY['pois chiches','légumineuses','protéines']),
('chickpeas-superc', 'superc', 'Pois chiches', 'Selection', '540ml', 540, 'ml', 1.69, 0.00313, false, false, ARRAY['pois chiches','légumineuses','protéines']),
('kidney-metro', 'metro', 'Haricots rouges en conserve', 'Unico', '540ml', 540, 'ml', 1.99, 0.00369, false, false, ARRAY['haricots rouges','légumineuses']),
('kidney-walmart', 'walmart', 'Red Kidney Beans', 'Great Value', '540ml', 540, 'ml', 1.27, 0.00235, false, false, ARRAY['haricots rouges','légumineuses']),
('rice-metro', 'metro', 'Riz basmati blanc', 'Riviana', '2kg', 2000, 'g', 8.49, 0.00425, false, false, ARRAY['riz','céréales','glucides']),
('rice-walmart', 'walmart', 'Long Grain White Rice', 'Great Value', '2kg', 2000, 'g', 5.47, 0.00274, false, false, ARRAY['riz','céréales','glucides']),
('rice-iga', 'iga', 'Riz à grain long', 'Uncle Ben''s', '1.8kg', 1800, 'g', 7.99, 0.00444, false, false, ARRAY['riz','céréales','glucides']),
('rice-superc', 'superc', 'Riz blanc à grain long', 'Selection', '2kg', 2000, 'g', 6.49, 0.00325, false, false, ARRAY['riz','céréales','glucides']),
('rice-maxi', 'maxi', 'Riz basmati', 'Elephant', '2kg', 2000, 'g', 7.29, 0.00365, false, false, ARRAY['riz','céréales','glucides']),
('bulgur-metro', 'metro', 'Boulgour', 'Unico', '500g', 500, 'g', 3.99, 0.00798, false, false, ARRAY['boulgour','céréales','glucides']),
('bulgur-walmart', 'walmart', 'Bulgur Wheat', 'Great Value', '500g', 500, 'g', 2.97, 0.00594, false, false, ARRAY['boulgour','céréales','glucides']),
('pasta-metro', 'metro', 'Spaghetti no. 7', 'Barilla', '500g', 500, 'g', 2.49, 0.00498, false, false, ARRAY['pâtes','céréales','glucides']),
('pasta-walmart', 'walmart', 'Spaghetti', 'Great Value', '900g', 900, 'g', 1.97, 0.00219, false, false, ARRAY['pâtes','céréales','glucides']),
('bread-metro', 'metro', 'Pain complet tranche', 'Villaggio', '570g', 570, 'g', 4.99, 0.00876, false, false, ARRAY['pain','céréales']),
('bread-walmart', 'walmart', 'Whole Wheat Bread', 'Great Value', '675g', 675, 'g', 2.97, 0.00440, false, false, ARRAY['pain','céréales']),
('wrap-metro', 'metro', 'Wraps de blé complet', 'Mission', '8 unités', 8, 'unités', 4.99, 0.624, false, false, ARRAY['wrap','pain','céréales']),
('cracker-metro', 'metro', 'Galettes de seigle', 'Wasa', '270g', 270, 'g', 4.29, 0.01589, false, false, ARRAY['crackers','pain','céréales']),
('cracker-walmart', 'walmart', 'Rye Crispbread', 'Finn Crisp', '200g', 200, 'g', 3.47, 0.01735, false, false, ARRAY['crackers','pain','céréales']),
('chicken-metro', 'metro', 'Poitrines de poulet sans os', 'Maple Leaf', '900g', 900, 'g', 13.99, 0.01554, false, false, ARRAY['poulet','viande','protéines']),
('chicken-iga', 'iga', 'Poitrines de poulet', 'Ferme Famille Goulet', '800g', 800, 'g', 12.99, 0.01624, false, true, ARRAY['poulet','viande','protéines']),
('chicken-walmart', 'walmart', 'Chicken Breast Boneless', 'Great Value', '1kg', 1000, 'g', 10.97, 0.01097, false, false, ARRAY['poulet','viande','protéines']),
('chicken-superc', 'superc', 'Poitrines de poulet', 'Selection', '1kg', 1000, 'g', 11.49, 0.01149, false, false, ARRAY['poulet','viande','protéines']),
('chicken-maxi', 'maxi', 'Poitrines poulet sans os', 'Olymel', '1kg', 1000, 'g', 11.99, 0.01199, false, false, ARRAY['poulet','viande','protéines']),
('turkey-metro', 'metro', 'Filet de dinde', 'Maple Leaf', '600g', 600, 'g', 10.99, 0.01832, false, false, ARRAY['dinde','viande','protéines']),
('turkey-walmart', 'walmart', 'Turkey Breast', 'Great Value', '800g', 800, 'g', 9.97, 0.01246, false, false, ARRAY['dinde','viande','protéines']),
('turkey-iga', 'iga', 'Blanc de dinde', 'Olymel', '600g', 600, 'g', 10.49, 0.01748, false, false, ARRAY['dinde','viande','protéines']),
('beef-metro', 'metro', 'Bœuf haché extra-maigre', 'Maple Leaf', '500g', 500, 'g', 9.99, 0.01998, false, false, ARRAY['bœuf','viande','protéines']),
('beef-walmart', 'walmart', 'Lean Ground Beef', 'Great Value', '500g', 500, 'g', 7.97, 0.01594, false, false, ARRAY['bœuf','viande','protéines']),
('beef-iga', 'iga', 'Bœuf haché maigre', 'Local', '500g', 500, 'g', 9.49, 0.01898, false, true, ARRAY['bœuf','viande','protéines']),
('tuna-metro', 'metro', 'Thon au naturel', 'Clover Leaf', '170g', 170, 'g', 2.49, 0.01465, false, false, ARRAY['thon','poisson','conserve','protéines']),
('tuna-walmart', 'walmart', 'Tuna in Water', 'Great Value', '170g', 170, 'g', 1.47, 0.00865, false, false, ARRAY['thon','poisson','conserve','protéines']),
('tuna-iga', 'iga', 'Thon albacore au naturel', 'Compliments', '170g', 170, 'g', 2.29, 0.01347, false, false, ARRAY['thon','poisson','conserve','protéines']),
('tuna-superc', 'superc', 'Thon au naturel', 'Selection', '170g', 170, 'g', 1.99, 0.01171, false, false, ARRAY['thon','poisson','conserve','protéines']),
('tuna-maxi', 'maxi', 'Thon au naturel', 'Clover Leaf', '170g', 170, 'g', 2.39, 0.01406, false, false, ARRAY['thon','poisson','conserve','protéines']),
('salmon-metro', 'metro', 'Filets de saumon Atlantique', 'Generic', '400g', 400, 'g', 12.99, 0.03248, false, false, ARRAY['saumon','poisson','protéines']),
('salmon-iga', 'iga', 'Saumon Atlantique frais', 'Clearwater', '400g', 400, 'g', 13.49, 0.03373, false, false, ARRAY['saumon','poisson','protéines']),
('salmon-walmart', 'walmart', 'Atlantic Salmon Fillet', 'Generic', '500g', 500, 'g', 11.97, 0.02394, false, false, ARRAY['saumon','poisson','protéines']),
('salmon-superc', 'superc', 'Filet de saumon', 'Generic', '400g', 400, 'g', 11.99, 0.02998, false, false, ARRAY['saumon','poisson','protéines']),
('salmon-fume-metro', 'metro', 'Saumon fumé tranché', 'Clearwater', '150g', 150, 'g', 8.99, 0.05993, false, false, ARRAY['saumon fumé','saumon','poisson']),
('salmon-fume-iga', 'iga', 'Saumon fumé du Pacifique', 'Irresistibles', '150g', 150, 'g', 8.49, 0.05660, false, false, ARRAY['saumon fumé','saumon','poisson']),
('cod-metro', 'metro', 'Filet de cabillaud', 'Generic', '400g', 400, 'g', 9.99, 0.02498, false, false, ARRAY['cabillaud','poisson','protéines']),
('cod-walmart', 'walmart', 'Cod Fillet', 'Highliner', '500g', 500, 'g', 9.47, 0.01894, false, false, ARRAY['cabillaud','poisson','protéines']),
('shrimp-metro', 'metro', 'Crevettes nordiques cuites', 'Clearwater', '400g', 400, 'g', 11.99, 0.02998, false, false, ARRAY['crevettes','poisson','protéines']),
('shrimp-walmart', 'walmart', 'Cooked Shrimp Peeled', 'Great Value', '454g', 454, 'g', 8.97, 0.01976, false, false, ARRAY['crevettes','poisson','protéines']),
('berries-metro', 'metro', 'Mélange baies surgelées', 'M''Lord', '600g', 600, 'g', 7.49, 0.01248, false, false, ARRAY['baies','fruits','surgelé']),
('berries-iga', 'iga', 'Baies mélangées surgelées', 'Irresistibles', '600g', 600, 'g', 7.29, 0.01215, false, false, ARRAY['baies','fruits','surgelé']),
('berries-walmart', 'walmart', 'Mixed Berries Frozen', 'Great Value', '750g', 750, 'g', 6.47, 0.00863, false, false, ARRAY['baies','fruits','surgelé']),
('berries-superc', 'superc', 'Mélange 3 fruits surgelés', 'Selection', '600g', 600, 'g', 6.99, 0.01165, false, false, ARRAY['baies','fruits','surgelé']),
('berries-maxi', 'maxi', 'Baies sauvages surgelées', 'Compliments', '600g', 600, 'g', 6.79, 0.01132, false, false, ARRAY['baies','fruits','surgelé']),
('blueberries-org', 'metro', 'Bleuets biologiques surgelés', 'Nature''s Touch', '600g', 600, 'g', 9.99, 0.01665, true, true, ARRAY['baies','bleuets','bio','surgelé']),
('mango-metro', 'metro', 'Dés de mangue surgelés', 'Generic', '400g', 400, 'g', 4.99, 0.01248, false, false, ARRAY['mangue','fruits','surgelé']),
('mango-walmart', 'walmart', 'Mango Chunks Frozen', 'Great Value', '400g', 400, 'g', 3.97, 0.00993, false, false, ARRAY['mangue','fruits','surgelé']),
('banana-metro', 'metro', 'Bananes', 'Dole', '1 régime (~6)', 6, 'unités', 1.99, 0.332, false, false, ARRAY['banane','fruits']),
('banana-walmart', 'walmart', 'Bananas', 'Generic', '1.36kg', 1360, 'g', 1.57, 0.00115, false, false, ARRAY['banane','fruits']),
('banana-superc', 'superc', 'Bananes', 'Generic', '1kg', 1000, 'g', 1.29, 0.00129, false, false, ARRAY['banane','fruits']),
('avocado-metro', 'metro', 'Avocats Hass', 'Generic', '3 unités', 3, 'unités', 4.99, 1.663, false, false, ARRAY['avocat','fruits','légumes']),
('avocado-walmart', 'walmart', 'Avocados', 'Generic', '4 unités', 4, 'unités', 4.97, 1.243, false, false, ARRAY['avocat','fruits','légumes']),
('avocado-iga', 'iga', 'Avocats mûrs', 'Generic', '2 unités', 2, 'unités', 3.49, 1.745, false, false, ARRAY['avocat','fruits','légumes']),
('sweetpotato-metro', 'metro', 'Patates douces', 'Generic', '1.5kg', 1500, 'g', 5.99, 0.00399, false, false, ARRAY['patate douce','légumes','glucides']),
('sweetpotato-walmart', 'walmart', 'Sweet Potatoes', 'Generic', '2kg', 2000, 'g', 5.97, 0.00299, false, false, ARRAY['patate douce','légumes','glucides']),
('sweetpotato-iga', 'iga', 'Patates douces orange', 'Generic', '1kg', 1000, 'g', 4.49, 0.00449, false, false, ARRAY['patate douce','légumes','glucides']),
('spinach-metro', 'metro', 'Épinards frais', 'Earthbound Farm', '142g', 142, 'g', 4.99, 0.03514, false, false, ARRAY['épinards','légumes','salade']),
('spinach-walmart', 'walmart', 'Baby Spinach', 'Great Value', '340g', 340, 'g', 4.97, 0.01462, false, false, ARRAY['épinards','légumes','salade']),
('spinach-iga', 'iga', 'Bébés épinards', 'Attitude Fraîche', '142g', 142, 'g', 4.79, 0.03373, false, true, ARRAY['épinards','légumes','salade']),
('spinach-superc', 'superc', 'Épinards bébé', 'Selection', '142g', 142, 'g', 3.99, 0.02810, false, false, ARRAY['épinards','légumes','salade']),
('courgette-metro', 'metro', 'Courgettes vertes', 'Generic', '3 unités (~600g)', 600, 'g', 3.99, 0.00665, false, true, ARRAY['courgette','légumes']),
('courgette-walmart', 'walmart', 'Zucchini', 'Generic', '~500g', 500, 'g', 2.97, 0.00594, false, false, ARRAY['courgette','légumes']),
('courgette-iga', 'iga', 'Courgettes', 'Generic', '2 unités (~400g)', 400, 'g', 3.49, 0.00873, false, true, ARRAY['courgette','légumes']),
('pepper-metro', 'metro', 'Poivrons tricolores', 'Generic', '3 unités', 3, 'unités', 5.99, 1.997, false, true, ARRAY['poivron','légumes']),
('pepper-walmart', 'walmart', 'Bell Peppers', 'Generic', '3 unités', 3, 'unités', 4.97, 1.657, false, false, ARRAY['poivron','légumes']),
('broccoli-metro', 'metro', 'Brocoli', 'Generic', '1 tête (~500g)', 500, 'g', 3.49, 0.00698, false, true, ARRAY['brocoli','légumes']),
('broccoli-walmart', 'walmart', 'Broccoli Crown', 'Generic', '1 tête (~500g)', 500, 'g', 2.97, 0.00594, false, false, ARRAY['brocoli','légumes']),
('tomato-metro', 'metro', 'Tomates en dés', 'Del Monte', '796ml', 796, 'ml', 2.49, 0.00313, false, false, ARRAY['tomates','conserve','légumes']),
('tomato-walmart', 'walmart', 'Diced Tomatoes', 'Great Value', '796ml', 796, 'ml', 1.47, 0.00185, false, false, ARRAY['tomates','conserve','légumes']),
('tomato-cherry-metro', 'metro', 'Tomates cerises', 'Generic', '454g', 454, 'g', 3.99, 0.00879, false, true, ARRAY['tomates cerises','tomates','légumes']),
('tomato-cherry-iga', 'iga', 'Tomates raisins', 'Generic', '454g', 454, 'g', 4.29, 0.00945, false, true, ARRAY['tomates cerises','tomates','légumes']),
('cucumber-metro', 'metro', 'Concombre anglais', 'Generic', '1 unité', 1, 'unités', 1.99, 1.990, false, true, ARRAY['concombre','légumes']),
('cucumber-walmart', 'walmart', 'English Cucumber', 'Generic', '1 unité', 1, 'unités', 1.47, 1.470, false, false, ARRAY['concombre','légumes']),
('onion-metro', 'metro', 'Oignons jaunes', 'Generic', '3lb (~1.36kg)', 1360, 'g', 3.99, 0.00293, false, true, ARRAY['oignons','légumes']),
('onion-walmart', 'walmart', 'Yellow Onions', 'Generic', '3lb (~1.36kg)', 1360, 'g', 2.97, 0.00218, false, false, ARRAY['oignons','légumes']),
('garlic-metro', 'metro', 'Ail frais', 'Generic', '3 têtes', 3, 'têtes', 2.49, 0.830, false, true, ARRAY['ail','légumes']),
('garlic-walmart', 'walmart', 'Garlic bulbs', 'Generic', '3 bulbes', 3, 'têtes', 1.97, 0.657, false, false, ARRAY['ail','légumes']),
('beet-metro', 'metro', 'Betteraves cuites sous vide', 'Generic', '500g', 500, 'g', 4.49, 0.00898, false, true, ARRAY['betterave','légumes']),
('beet-walmart', 'walmart', 'Cooked Beets', 'Great Value', '500g', 500, 'g', 3.47, 0.00694, false, false, ARRAY['betterave','légumes']),
('oliveoil-metro', 'metro', 'Huile d''olive extra vierge', 'Bertolli', '750ml', 750, 'ml', 12.99, 0.01732, false, false, ARRAY['huile olive','huile','gras']),
('oliveoil-walmart', 'walmart', 'Extra Virgin Olive Oil', 'Great Value', '1L', 1000, 'ml', 9.97, 0.00997, false, false, ARRAY['huile olive','huile','gras']),
('oliveoil-iga', 'iga', 'Huile d''olive vierge extra', 'Carbonell', '750ml', 750, 'ml', 11.99, 0.01599, false, false, ARRAY['huile olive','huile','gras']),
('oliveoil-superc', 'superc', 'Huile d''olive extra vierge', 'Selection', '750ml', 750, 'ml', 10.49, 0.01399, false, false, ARRAY['huile olive','huile','gras']),
('almond-milk-metro', 'metro', 'Boisson d''amande non sucrée', 'Silk', '1.89L', 1890, 'ml', 4.99, 0.00264, false, false, ARRAY['lait végétal','lait','dairy-free']),
('almond-milk-walmart', 'walmart', 'Unsweetened Almond Milk', 'Great Value', '1.89L', 1890, 'ml', 3.97, 0.00210, false, false, ARRAY['lait végétal','lait','dairy-free']),
('soy-milk-metro', 'metro', 'Boisson de soja nature', 'Natrel', '1L', 1000, 'ml', 2.99, 0.00299, false, false, ARRAY['lait végétal','lait','dairy-free']),
('oat-milk-metro', 'metro', 'Boisson d''avoine', 'Oatly', '1L', 1000, 'ml', 4.49, 0.00449, false, false, ARRAY['lait végétal','lait','dairy-free']),
('milk-metro', 'metro', 'Lait 2%', 'Lactantia', '2L', 2000, 'ml', 4.99, 0.00250, false, true, ARRAY['lait','dairy']),
('milk-walmart', 'walmart', '2% Partly Skimmed Milk', 'Great Value', '2L', 2000, 'ml', 3.97, 0.00199, false, false, ARRAY['lait','dairy']),
('walnuts-metro', 'metro', 'Cerneaux de noix', 'Generic', '200g', 200, 'g', 5.99, 0.02995, false, false, ARRAY['noix','oléagineux']),
('almonds-metro', 'metro', 'Amandes entières', 'Blue Diamond', '200g', 200, 'g', 5.49, 0.02745, false, false, ARRAY['amandes','oléagineux']),
('chia-metro', 'metro', 'Graines de chia', 'Genuine Health', '300g', 300, 'g', 7.99, 0.02663, true, false, ARRAY['chia','graines']),
('chia-walmart', 'walmart', 'Chia Seeds', 'Great Value', '300g', 300, 'g', 5.97, 0.01990, false, false, ARRAY['chia','graines']),
('flax-metro', 'metro', 'Graines de lin moulues', 'Omega', '400g', 400, 'g', 4.99, 0.01248, false, false, ARRAY['lin','graines']),
('almond-butter-metro', 'metro', 'Beurre d''amandes naturel', 'Krema', '500g', 500, 'g', 10.99, 0.02198, false, false, ARRAY['beurre amandes','noix','protéines']),
('peanut-butter-metro', 'metro', 'Beurre d''arachide naturel', 'Kraft', '1kg', 1000, 'g', 8.99, 0.00899, false, false, ARRAY['beurre arachide','noix','protéines']),
('peanut-butter-walmart', 'walmart', 'Peanut Butter Natural', 'Great Value', '1kg', 1000, 'g', 6.97, 0.00697, false, false, ARRAY['beurre arachide','noix','protéines']),
('honey-metro', 'metro', 'Miel pur blanc', 'Billy Bee', '500g', 500, 'g', 7.99, 0.01598, false, true, ARRAY['miel']),
('honey-walmart', 'walmart', 'Pure Honey', 'Great Value', '500g', 500, 'g', 5.97, 0.01194, false, false, ARRAY['miel']),
('hummus-metro', 'metro', 'Hummus nature', 'Fontaine Santé', '340g', 340, 'g', 4.99, 0.01468, false, true, ARRAY['hummus']),
('hummus-walmart', 'walmart', 'Classic Hummus', 'Sabra', '340g', 340, 'g', 4.47, 0.01315, false, false, ARRAY['hummus']),
('soy-sauce-metro', 'metro', 'Sauce soja légère', 'Kikkoman', '250ml', 250, 'ml', 3.99, 0.01596, false, false, ARRAY['sauce soja','condiments']),
('soy-sauce-walmart', 'walmart', 'Soy Sauce Less Sodium', 'Great Value', '500ml', 500, 'ml', 2.97, 0.00594, false, false, ARRAY['sauce soja','condiments']),
('whey-metro', 'metro', 'Protéines whey vanille', 'Optimum Nutrition', '908g', 908, 'g', 44.99, 0.04955, false, false, ARRAY['whey','protéine','supplément']),
('whey-walmart', 'walmart', 'Whey Protein Vanilla', 'Kirkland', '1.13kg', 1130, 'g', 34.97, 0.03094, false, false, ARRAY['whey','protéine','supplément'])
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  package_size = EXCLUDED.package_size,
  package_qty = EXCLUDED.package_qty,
  package_unit = EXCLUDED.package_unit,
  price = EXCLUDED.price,
  price_per_unit = EXCLUDED.price_per_unit,
  is_organic = EXCLUDED.is_organic,
  is_local = EXCLUDED.is_local,
  tags = EXCLUDED.tags,
  updated_at = now();
